# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd0c6c55a99a4eacfcc67c9848cd38e80536c37a5ffdcb3677d29c023da8b142ee9264fba6d1308d9079170d2fce5dfe30001de5b15eb37ae62607f72e48f628

test:
  secret_key_base: d4ca90ce6a00761dfc9a6d6d3661e87a4fa23bf4f3653f3c6ec88be5c229a5950e87c4b1af260a57878e50e9cb14c01b45e69097e6d197276a889c83969f546c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
